apiVersion: apps/v1
kind: Deployment
metadata:
  name: smess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smess
  template:
    metadata:
      labels:
        app: smess
    spec:
      containers:
        - name: smess-container
          image: hndeau/smess:latest
          ports:
            - containerPort: 80
