apiVersion: apps/v1
kind: Deployment
metadata:
  name: SMess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SMess
  template:
    metadata:
      labels:
        app: SMess
    spec:
      containers:
        - name: smess
          image: hndeau/smess:latest
          ports:
            - containerPort: 80
